name: Pipeline run by go
env:
  NAME: Stefan
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.1'
    - run: go version 
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello ${{NAME}}'
    
 
